# Generated by Django 5.0.1 on 2025-10-30 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_issue_updates', models.BooleanField(default=True)),
                ('email_event_reminders', models.BooleanField(default=True)),
                ('email_forum_replies', models.BooleanField(default=True)),
                ('email_system_updates', models.BooleanField(default=True)),
                ('email_weekly_digest', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_verified', models.BooleanField(default=False)),
                ('whatsapp_issue_updates', models.BooleanField(default=True)),
                ('whatsapp_event_reminders', models.BooleanField(default=True)),
                ('whatsapp_system_alerts', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_issue_updates', models.BooleanField(default=True)),
                ('push_event_reminders', models.BooleanField(default=True)),
                ('push_forum_replies', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_critical_only', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='e.g., 22:00', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='e.g., 08:00', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
    ]
