# Generated by Django 5.0.1 on 2025-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievement_civiclevel_civicactivity_communitycredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
