# Generated by Django 5.0.1 on 2025-10-31 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code (e.g., +919725032474 or +14155551234)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: +[country code][number] (e.g., +919725032474)', regex='^\\+\\d{10,15}$')]),
        ),
    ]
