# Generated by Django 5.0.1 on 2025-09-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('district_type', models.CharField(choices=[('ward', 'Ward'), ('district', 'District'), ('neighborhood', 'Neighborhood'), ('zone', 'Zone')], default='district', max_length=50)),
                ('boundary_coordinates', models.JSONField(blank=True, default=list, help_text='Array of [lat, lng] coordinate pairs defining the boundary')),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('area_sq_km', models.FloatField(blank=True, null=True)),
                ('representative', models.CharField(blank=True, max_length=200)),
                ('representative_contact', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layer_type', models.CharField(choices=[('issues', 'Issues'), ('events', 'Events'), ('projects', 'Projects'), ('facilities', 'Public Facilities'), ('districts', 'Districts'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('default_visible', models.BooleanField(default=True)),
                ('min_zoom', models.PositiveIntegerField(default=0)),
                ('max_zoom', models.PositiveIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Map Layer',
                'verbose_name_plural': 'Map Layers',
                'db_table': 'map_layers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('hospital', 'Hospital'), ('school', 'School'), ('library', 'Library'), ('park', 'Park'), ('police_station', 'Police Station'), ('fire_station', 'Fire Station'), ('government_office', 'Government Office'), ('community_center', 'Community Center'), ('public_transport', 'Public Transport'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('is_accessible', models.BooleanField(default=False)),
                ('accessibility_features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Facility',
                'verbose_name_plural': 'Public Facilities',
                'db_table': 'public_facilities',
                'ordering': ['name'],
            },
        ),
    ]
